#!/bin/bash 
# written by AK 
# this script prepares a fortran script for post processing 
# the fortran program, post.f90 produces EPG_t.txt SHUY_t.txt for open dx and calculations of the gradients 
# and richardson numbers

echo TOPO file name? 

here=$(pwd)
cp ~/myprojects/sinchannels/sin_20_l400_w50/post.f90 $here
cp ~/myprojects/conversion.sh $here

cp ~/myprojects/sinchannels/sin_20_l400_w50/*.net $here
cp ~/myprojects/sinchannels/sin_20_l400_w50/*.general $here
cp ~/myprojects/sinchannels/sin_20_l400_w50/*.cfg $here

topo=$(sed -n '71 s/^[^=]*=*//p ' init_fvars.f)

topo2=${topo:1:-2}

echo $topo2

echo timesteps?
read time


sed -i.bak "78s|^.*$|OPEN(602, FILE='$topo2')|" post.f90
sed -i.bak "167s|^.*$|timesteps=$time|" post.f90



ifort post.f90 -convert big_endian -o post.exe

echo conversion script prepared
echo would you like to submit?Y/N
read answer


 if [ "$answer" == 'Y' ];then
                sbatch conversion.sh
		echo "postprocessing submitted" > status.txt
        else
                echo script complete
		echo "post processing prepared not submitted" > status.txt
        fi


