#!/bin/bash

echo here is a reminder of your naming conventions
echo "Wavelenth (m)// A:300, B:600, C:900, D:1200, S: straight"
echo "Width (m) // W:300, V:200, N:100"
echo "VolumeFlux (m^3/s)// 1:1000 4:4000 7:7000 0:10000"


