#!/bin/bash

echo here is a reminder of your naming conventions
echo "Wavelenth (m)// A:300, B:600, C:900, D:1200, S: straight"
echo "Width (m) // W:300, V:200, N:100"
echo "Inlet Height to Depth ratio // 1: 0.1 4: 0.4 7: 0.7 0: 1.0"


